// 🌟 關係子句 + 分詞簡化片語，6種題型各 25 題（總共 150 題終極題庫晶片）
const totalPool = [
    // === 題型一：基礎關代填空 (1-25 題) ===
    { type: 1, before: "Andrew lost ", antecedent: "the hat", clause: "was given by Sharon.", ans: ["which", "that"] },
    { type: 1, before: "My mom likes to watch ", antecedent: "dramas", clause: "talk about family matters.", ans: ["which", "that"] },
    { type: 1, before: "The boy ", antecedent: "the boy", after: " is my brother.", clause: "is standing by the door", ans: ["who", "that"], isEmbed: true },
    { type: 1, before: "I bought a book ", antecedent: "a book", clause: "has many beautiful pictures.", ans: ["which", "that"] },
    { type: 1, before: "The doctor ", antecedent: "the doctor", after: " was very kind.", clause: "treated my grandfather", ans: ["who", "that"], isEmbed: true },
    { type: 1, before: "They live in a house ", antecedent: "a house", clause: "is over one hundred years old.", ans: ["which", "that"] },
    { type: 1, before: "The singer ", antecedent: "the singer", after: " won the award.", clause: "sang the beautiful song", ans: ["who", "that"], isEmbed: true },
    // ⭕ 修正後：讓 before 結尾與 antecedent 完全一致，大螢幕就會啟動自動去重晶片！
    { type: 1, before: "He bought a new car ", antecedent: "a new car", clause: "runs on electricity.", ans: ["which", "that"] },
    { type: 1, before: "The teacher ", antecedent: "the teacher", after: " comes from Canada.", clause: "teaches us English", ans: ["who", "that"], isEmbed: true },
    { type: 1, before: "Look at the dog ", antecedent: "the dog", clause: "is barking at the mailman.", ans: ["which", "that"] },
    { type: 1, before: "The woman ", antecedent: "the woman", after: " is a famous lawyer.", clause: "lives next door", ans: ["who", "that"], isEmbed: true },
    { type: 1, before: "The restaurant ", antecedent: "the restaurant", clause: "serves delicious pizza closed early.", ans: ["which", "that"] },
    { type: 1, before: "I met a traveler ", antecedent: "a traveler", clause: "had just returned from Africa.", ans: ["who", "that"] },
    { type: 1, before: "The movie ", antecedent: "the movie", after: " was very scary.", clause: "we watched last night", ans: ["which", "that"], isEmbed: true },
    { type: 1, before: "The student ", antecedent: "the student", after: " got a perfect score.", clause: "studied the hardest", ans: ["who", "that"], isEmbed: true },
    { type: 1, before: "Please return the laptop ", antecedent: "the laptop", clause: "belongs to the office.", ans: ["which", "that"] },
    { type: 1, before: "The workers ", antecedent: "the workers", after: " demand higher wages.", clause: "built this tower", ans: ["who", "that"], isEmbed: true },
    { type: 1, before: "The letters ", antecedent: "the letters", after: " arrived this morning.", clause: "were on the desk", ans: ["which", "that"], isEmbed: true },
    { type: 1, before: "I don't like people ", antecedent: "people", clause: "tell lies to their friends.", ans: ["who", "that"] },
    { type: 1, before: "The tree ", antecedent: "the tree", after: " blew down in the storm.", clause: "stood in front of the house", ans: ["which", "that"], isEmbed: true },
    { type: 1, before: "The children ", antecedent: "the children", after: " are playing in the park.", clause: "live in this neighborhood", ans: ["who", "that"], isEmbed: true },
    { type: 1, before: "She works for a company ", antecedent: "a company", clause: "makes medical equipment.", ans: ["which", "that"] },
    { type: 1, before: "The jacket ", antecedent: "the jacket", after: " is made of leather.", clause: "is hanging in the closet", ans: ["which", "that"], isEmbed: true },
    { type: 1, before: "The scientist ", antecedent: "the scientist", after: " gave an inspiring speech.", clause: "discovered the new virus", ans: ["who", "that"], isEmbed: true },
    { type: 1, before: "He tells stories ", antecedent: "stories", clause: "sound completely unbelievable.", ans: ["which", "that"] },

    // === 題型二：尋找修飾標靶 (26-50 題) ===
    { type: 2, full: "The woman who is listening to music is an actress.", target: "who,is,listening,to,music" },
    { type: 2, full: "A crowd of people who gathered in the square were there for the event.", target: "who,gathered,in,the,square" },
    { type: 2, full: "I cannot find the keys which open the back door.", target: "which,open,the,back,door" },
    { type: 2, full: "The students who passed the English exam felt very happy.", target: "who,passed,the,English,exam" },
    { type: 2, full: "The multi-touch screen which was invented recently is amazing.", target: "which,was,invented,recently" },
    { type: 2, full: "The pocket computer that fits inside a pocket is called a smartphone.", target: "that,fits,inside,a,pocket" },
    { type: 2, full: "Do you know the gentleman who is wearing a black suit?", target: "who,is,wearing,a,black,suit" },
    { type: 2, full: "The library which stands on the hill will be rebuilt.", target: "which,stands,on,the,hill" },
    { type: 2, full: "The cake that was made by my sister tasted sweet.", target: "that,was,made,by,my,sister" },
    { type: 2, full: "The monkeys which live in the mountain are very friendly.", target: "which,live,in,the,mountain" },
    { type: 2, full: "The report which was written by Tom contains many mistakes.", target: "which,was,written,by,Tom" },
    { type: 2, full: "The passengers who were injured in the accident went to hospital.", target: "who,were,injured,in,the,accident" },
    { type: 2, full: "The store that sells organic food is always crowded.", target: "that,sells,organic,food" },
    { type: 2, full: "The artist who painted this beautiful mural is highly talented.", target: "who,painted,this,beautiful,mural" },
    { type: 2, full: "The package which arrived yesterday afternoon was for my dad.", target: "which,arrived,yesterday,afternoon" },
    { type: 2, full: "The guard who stands at the gate checks everyone's ID.", target: "who,stands,at,the,gate" },
    { type: 2, full: "The fruits that grow on this tree are not safe to eat.", target: "that,grow,on,this,tree" },
    { type: 2, full: "The website which provides online courses is free for students.", target: "which,provides,online,courses" },
    { type: 2, full: "The actor who played the main character won an Oscar.", target: "who,played,the,main,character" },
    { type: 2, full: "The heavy rain that caused the flash flood lasted for three hours.", target: "that,caused,the,flash,flood" },
    { type: 2, full: "The museum which displays ancient artifacts attracting many tourists.", target: "which,displays,ancient,artifacts" },
    { type: 2, full: "The teacher who coaches the basketball team is very strict.", target: "who,coaches,the,basketball,team" },
    { type: 2, full: "The machine that prints the labels is out of order.", target: "that,prints,the,labels" },
    { type: 2, full: "The flight which goes to New York has been delayed.", target: "which,goes,to,New,York" },
    { type: 2, full: "The uniform that is worn by the staff looks very elegant.", target: "that,is,worn,by,the,staff" },

    // === 題型三：文法拆解大師 (51-75 題) ===
    { type: 3, raw1: "I bought a book.", raw2: "It has many beautiful pictures.", before: "I bought a book ", options: ["which has many beautiful pictures.", "who has many beautiful pictures.", "has many beautiful pictures."], ans: "which has many beautiful pictures." },
    { type: 3, raw1: "I know a girl.", raw2: "She speaks four languages.", before: "I know a girl ", options: ["who speaks four languages.", "which speaks four languages.", "speaks four languages."], ans: "who speaks four languages." },
    { type: 3, raw1: "This is the bus.", raw2: "It goes to the station.", before: "This is the bus ", options: ["which goes to the station.", "who goes to the station.", "goes to the station."], ans: "which goes to the station." },
    { type: 3, raw1: "The man cooked dinner.", raw2: "He is a famous chef.", before: "The man ", after: " is a famous chef.", options: ["who cooked dinner", "which cooked dinner", "cooked dinner"], ans: "who cooked dinner", isEmbed: true },
    { type: 3, raw1: "The computer belongs to Tom.", raw2: "It is expensive.", before: "The computer ", after: " is expensive.", options: ["which belongs to Tom", "who belongs to Tom", "belongs to Tom"], ans: "which belongs to Tom", isEmbed: true },
    { type: 3, raw1: "We visited a museum.", raw2: "It displayed ancient arts.", before: "We visited a museum ", options: ["which displayed ancient arts.", "who displayed ancient arts.", "displayed ancient arts."], ans: "which displayed ancient arts." },
    { type: 3, raw1: "The girls are laughing.", raw2: "They sit under the tree.", before: "The girls ", after: " are laughing.", options: ["who sit under the tree", "which sit under the tree", "sit under the tree"], ans: "who sit under the tree", isEmbed: true },
    { type: 3, raw1: "I like the movie.", raw2: "It has a happy ending.", before: "I like the movie ", options: ["which has a happy ending.", "who has a happy ending.", "has a happy ending."], ans: "which has a happy ending." },
    { type: 3, raw1: "The phone was broken.", raw2: "It was on the table.", before: "The phone ", after: " was broken.", options: ["which was on the table", "who was on the table", "was on the table"], ans: "which was on the table", isEmbed: true },
    { type: 3, raw1: "The officer was helpful.", raw2: "He answered my questions.", before: "The officer ", after: " was helpful.", options: ["who answered my questions", "which answered my questions", "answered my questions"], ans: "who answered my questions", isEmbed: true },
    { type: 3, raw1: "She has a cat.", raw2: "It loves to sleep on the sofa.", before: "She has a cat ", options: ["which loves to sleep on the sofa.", "who loves to sleep on the sofa.", "loves to sleep on the sofa."], ans: "which loves to sleep on the sofa." },
    { type: 3, raw1: "They met the author.", raw2: "He wrote the best book.", before: "They met the author ", options: ["who wrote the best book.", "which wrote the best book.", "wrote the best book."], ans: "who wrote the best book." },
    { type: 3, raw1: "The watch is a gift.", raw2: "It is made of gold.", before: "The watch ", after: " is a gift.", options: ["which is made of gold", "who is made of gold", "is made of gold"], ans: "which is made of gold", isEmbed: true },
    { type: 3, raw1: "The boy was praised.", raw2: "He saved the puppy.", before: "The boy ", after: " was praised.", options: ["who saved the puppy", "which saved the puppy", "saved the puppy"], ans: "who saved the puppy", isEmbed: true },
    { type: 3, raw1: "I live in an apartment.", raw2: "It overlooks the park.", before: "I live in an apartment ", options: ["which overlooks the park.", "who overlooks the park.", "overlooks the park."], ans: "which overlooks the park." },
    { type: 3, raw1: "The building was destroyed.", raw2: "It stood here.", before: "The building ", after: " was destroyed.", options: ["which stood here", "who stood here", "stood here"], ans: "which stood here", isEmbed: true },
    { type: 3, raw1: "The student won the scholarship.", raw2: "She works hard.", before: "The student ", after: " won the scholarship.", options: ["who works hard", "which works hard", "works hard"], ans: "who works hard", isEmbed: true },
    { type: 3, raw1: "This is the photo.", raw2: "It reminds me of summer.", before: "This is the photo ", options: ["which reminds me of summer.", "who reminds me of summer.", "reminds me of summer."], ans: "which reminds me of summer." },
    { type: 3, raw1: "The firemen were brave.", raw2: "They put out the fire.", before: "The firemen ", after: " were brave.", options: ["who put out the fire", "which put out the fire", "put out the fire"], ans: "who put out the fire", isEmbed: true },
    { type: 3, raw1: "He lost the wallet.", raw2: "It contained his ID card.", before: "He lost the wallet ", options: ["which contained his ID card.", "who contained his ID card.", "contained his ID card."], ans: "which contained his ID card." },
    { type: 3, raw1: "The cake was delicious.", raw2: "It had fresh strawberries.", before: "The cake ", after: " was delicious.", options: ["which had fresh strawberries", "who had fresh strawberries", "had fresh strawberries"], ans: "which had fresh strawberries", isEmbed: true },
    { type: 3, raw1: "I know the dentist.", raw2: "He pulled out your tooth.", before: "I know the dentist ", options: ["who pulled out your tooth.", "which pulled out your tooth.", "pulled out your tooth."], ans: "who pulled out your tooth." },
    { type: 3, raw1: "The shoes are tight.", raw2: "I bought them yesterday.", before: "The shoes ", after: " are tight.", options: ["which were bought yesterday", "who were bought yesterday", "were bought yesterday"], ans: "which were bought yesterday", isEmbed: true },
    { type: 3, raw1: "The people were friendly.", raw2: "They welcomed us.", before: "The people ", after: " were friendly.", options: ["who welcomed us", "which welcomed us", "welcomed us"], ans: "who welcomed us", isEmbed: true },
    { type: 3, raw1: "The contract was signed.", raw2: "It binds the two firms.", before: "The contract ", after: " was signed.", options: ["which binds the two firms", "who binds the two firms", "binds the two firms"], ans: "which binds the two firms", isEmbed: true },

    // === 題型四：高級排列組合 (76-100 題) ===
    { type: 4, raw1: "I know a girl.", raw2: "She speaks four languages.", tokens: ["I know a girl", "who", "speaks four languages."], ans: "I know a girl,who,speaks four languages." },
    { type: 4, raw1: "This is the bus.", raw2: "It goes to the station.", tokens: ["This is the bus", "which", "goes to the station."], ans: "This is the bus,which,goes to the station." },
    { type: 4, raw1: "The man cooked dinner.", raw2: "He is a chef.", tokens: ["The man", "who", "cooked dinner", "is a chef."], ans: "The man,who,cooked dinner,is a chef.||The man,who,is a chef,cooked dinner" },
    { type: 4, raw1: "The computer belongs to Tom.", raw2: "It is expensive.", tokens: ["The computer", "which", "belongs to Tom", "is expensive."], ans: "The computer,which,belongs to Tom,is expensive.||The computer,which,is expensive,belongs to Tom" },
    { type: 4, raw1: "We visited a museum.", raw2: "It displayed ancient arts.", tokens: ["We visited a museum", "which", "displayed ancient arts."], ans: "We visited a museum,which,displayed ancient arts." },
    { type: 4, raw1: "The girls are laughing.", raw2: "They sit under the tree.", tokens: ["The girls", "who", "sit under the tree", "are laughing."], ans: "The girls,who,sit under the tree,are laughing.||The girls,who,are laughing,sit under the tree" },
    { type: 4, raw1: "I like the movie.", raw2: "It has a happy ending.", tokens: ["I like the movie", "which", "has a happy ending."], ans: "I like the movie,which,has a happy ending." },
    { type: 4, raw1: "The phone was broken.", raw2: "It was on the table.", tokens: ["The phone", "which", "was on the table", "was broken."], ans: "The phone,which,was on the table,was broken.||The phone,which,was broken,was on the table" },
    { type: 4, raw1: "The officer was helpful.", raw2: "He answered my questions.", tokens: ["The officer", "who", "answered my questions", "was helpful."], ans: "The officer,who,answered my questions,was helpful.||The officer,who,was helpful,answered my questions" },
    { type: 4, raw1: "She has a cat.", raw2: "It loves to sleep on the sofa.", tokens: ["She has a cat", "which", "loves to sleep on the sofa."], ans: "She has a cat,which,loves to sleep on the sofa." },
    { type: 4, raw1: "They met the author.", raw2: "He wrote the best book.", tokens: ["They met the author", "who", "wrote the best book."], ans: "They met the author,who,wrote the best book." },
    { type: 4, raw1: "The watch is a gift.", raw2: "It is made of gold.", tokens: ["The watch", "which", "is made of gold", "is a gift."], ans: "The watch,which,is made of gold,is a gift.||The watch,which,is a gift,is made of gold" },
    { type: 4, raw1: "The boy was praised.", raw2: "He saved the puppy.", tokens: ["The boy", "who", "saved the puppy", "was praised."], ans: "The boy,who,saved the puppy,was praised.||The boy,who,was praised,saved the puppy" },
    { type: 4, raw1: "I live in an apartment.", raw2: "It overlooks the park.", tokens: ["I live in an apartment", "which", "overlooks the park."], ans: "I live in an apartment,which,overlooks the park." },
    { type: 4, raw1: "The building was destroyed.", raw2: "It stood here.", tokens: ["The building", "which", "stood here", "was destroyed."], ans: "The building,which,stood here,was destroyed.||The building,which,was destroyed,stood here" },
    { type: 4, raw1: "The student won the scholarship.", raw2: "She works hard.", tokens: ["The student", "who", "works hard", "won the scholarship."], ans: "The student,who,works hard,won the scholarship.||The student,who,won the scholarship,works hard" },
    { type: 4, raw1: "This is the photo.", raw2: "It reminds me of summer.", tokens: ["This is the photo", "which", "reminds me of summer."], ans: "This is the photo,which,reminds me of summer." },
    { type: 4, raw1: "The firemen were brave.", raw2: "They put out the fire.", tokens: ["The firemen", "who", "put out the fire", "were brave."], ans: "The firemen,who,put out the fire,were brave.||The firemen,who,were brave,put out the fire" },
    { type: 4, raw1: "He lost the wallet.", raw2: "It contained his ID card.", tokens: ["He lost the wallet", "which", "contained his ID card."], ans: "He lost the wallet,which,contained his ID card." },
    { type: 4, raw1: "The cake was delicious.", raw2: "It had fresh strawberries.", tokens: ["The cake", "which", "had fresh strawberries", "was delicious."], ans: "The cake,which,had fresh strawberries,was delicious.||The cake,which,was delicious,had fresh strawberries" },
    { type: 4, raw1: "I know the dentist.", raw2: "He pulled out your tooth.", tokens: ["I know the dentist", "who", "pulled out your tooth."], ans: "I know the dentist,who,pulled out your tooth." },
    { type: 4, raw1: "The shoes are tight.", raw2: "I bought them yesterday.", tokens: ["The shoes", "which", "were bought yesterday", "are tight."], ans: "The shoes,which,were bought yesterday,are tight.||The shoes,which,are tight,were bought yesterday" },
    { type: 4, raw1: "The people were friendly.", raw2: "They welcomed us.", tokens: ["The people", "who", "welcomed us", "were friendly."], ans: "The people,who,welcomed us,were friendly.||The people,who,were friendly,welcomed us" },
    { type: 4, raw1: "The contract was signed.", raw2: "It binds the two firms.", tokens: ["The contract", "which", "binds the two firms", "was signed."], ans: "The contract,which,binds the two firms,was signed.||The contract,which,was signed,binds the two firms" },
    { type: 4, raw1: "He adopted a puppy.", raw2: "It has floppy brown ears.", tokens: ["He adopted a puppy", "which", "has floppy brown ears."], ans: "He adopted a puppy,which,has floppy brown ears." },

    // === 🌟 題型五：關係子句簡化為分詞片語 - 觀念發射法 (101-125 題) ===
    // 💡 設計：大螢幕挖空 [ ❓ ]，提供 3 個分詞按鈕給學生平板進行秒殺搶答
    { type: 5, before: "I know a girl [ ❓ ] four languages.", options: ["speaking", "spoken", "speaks"], ans: "speaking" },
    { type: 5, before: "The man [ ❓ ] next door is a famous chef.", options: ["living", "lived", "lives"], ans: "living" },
    { type: 5, before: "Students [ ❓ ] to pass the exam must study hard.", options: ["wanting", "wanted", "wants"], ans: "wanting" },
    { type: 5, before: "The bus [ ❓ ] to the airport leaves every ten minutes.", options: ["going", "gone", "goes"], ans: "going" },
    { type: 5, before: "People [ ❓ ] lies to their friends will lose trust.", options: ["telling", "told", "tells"], ans: "telling" },
    { type: 5, before: "The river [ ❓ ] behind the factory is highly polluted.", options: ["running", "run", "runs"], ans: "running" },
    { type: 5, before: "She works for a company [ ❓ ] medical equipment.", options: ["making", "made", "makes"], ans: "making" },
    { type: 5, before: "The road [ ❓ ] the two towns is very narrow.", options: ["connecting", "connected", "connects"], ans: "connecting" },
    { type: 5, before: "Anyone [ ❓ ] the school rules will be punished.", options: ["breaking", "broken", "breaks"], ans: "breaking" },
    { type: 5, before: "The guard [ ❓ ] at the gate checks everyone's ID.", options: ["standing", "stood", "stands"], ans: "standing" },
    { type: 5, before: "Andrew lost the hat [ ❓ ] by Sharon.", options: ["given", "giving", "gives"], ans: "given" },
    { type: 5, before: "The multi-touch screen [ ❓ ] recently is amazing.", options: ["invented", "inventing", "invents"], ans: "invented" },
    { type: 5, before: "The cake [ ❓ ] by my sister tasted sweet.", options: ["made", "making", "makes"], ans: "made" },
    { type: 5, before: "The report [ ❓ ] by Tom contains many mistakes.", options: ["written", "writing", "writes"], ans: "written" },
    { type: 5, before: "The jacket [ ❓ ] of leather is hanging in the closet.", options: ["made", "making", "makes"], ans: "made" },
    { type: 5, before: "The uniform [ ❓ ] by the staff looks very elegant.", options: ["worn", "wearing", "wears"], ans: "worn" },
    { type: 5, before: "The book [ ❓ ] by a local author won first prize.", options: ["written", "writing", "writes"], ans: "written" },
    { type: 5, before: "The house [ ❓ ] in the fire stood on the hill.", options: ["destroyed", "destroying", "destroys"], ans: "destroyed" },
    { type: 5, before: "Cars [ ❓ ] from Germany are more expensive.", options: ["imported", "importing", "imports"], ans: "imported" },
    { type: 5, before: "The artifacts [ ❓ ] in the museum attract many tourists.", options: ["displayed", "displaying", "displays"], ans: "displayed" },
    { type: 5, before: "The boy [ ❓ ] by the door is my brother.", options: ["standing", "stood", "stands"], ans: "standing" },
    { type: 5, before: "The girls [ ❓ ] under the tree are laughing.", options: ["sitting", "sat", "sits"], ans: "sitting" },
    { type: 5, before: "Look at the dog [ ❓ ] at the mailman.", options: ["barking", "barked", "barks"], ans: "barking" },
    { type: 5, before: "Do you know the gentleman [ ❓ ] a black suit?", options: ["wearing", "worn", "wears"], ans: "wearing" },
    { type: 5, before: "The woman [ ❓ ] near the window looks lonely.", options: ["sitting", "sat", "sits"], ans: "sitting" },

    // === 🌟 題型六：關係子句簡化為分詞片語 - 磁鐵重組法 (126-150 題) ===
    // 💡 設計：大螢幕秀出原完整提示句，平板給予去除關代與 be 的大型簡化磁鐵進行卡位重組
    { type: 6, raw1: "I waved to passengers who were waving from the train.", tokens: ["I waved to passengers", "waving from the train."], ans: "I waved to passengers,waving from the train." },
    { type: 6, raw1: "The birds which were singing outside woke me up.", tokens: ["The birds", "singing outside", "woke me up."], ans: "The birds,singing outside,woke me up." },
    { type: 6, raw1: "The baby who was crying just now fell asleep.", tokens: ["The baby", "crying just now", "fell asleep."], ans: "The baby,crying just now,fell asleep." },
    { type: 6, raw1: "The police want the man who is running away in a jacket.", tokens: ["The police want the man", "running away in a jacket."], ans: "The police want the man,running away in a jacket." },
    { type: 6, raw1: "The stars which are shining in the sky look bright.", tokens: ["The stars", "shining in the sky", "look bright."], ans: "The stars,shining in the sky,look bright." },
    { type: 6, raw1: "The uniform that is worn by the staff looks elegant.", tokens: ["The uniform", "worn by the staff", "looks elegant."], ans: "The uniform,worn by the staff,looks elegant." },
    { type: 6, raw1: "The book which was written by a local author won.", tokens: ["The book", "written by a local author", "won."], ans: "The book,written by a local author,won." },
    { type: 6, raw1: "The house which was destroyed in the fire stood here.", tokens: ["The house", "destroyed in the fire", "stood here."], ans: "The house,destroyed in the fire,stood here." },
    { type: 6, raw1: "Cars which are imported from Germany are costly.", tokens: ["Cars", "imported from Germany", "are costly."], ans: "Cars,imported from Germany,are costly." },
    { type: 6, raw1: "Artifacts which are displayed in the museum attract fans.", tokens: ["Artifacts", "displayed in the museum", "attract fans."], ans: "Artifacts,displayed in the museum,attract fans." },
    { type: 6, raw1: "The river which runs behind the factory is polluted.", tokens: ["The river", "running behind the factory", "is polluted."], ans: "The river,running behind the factory,is polluted." },
    { type: 6, raw1: "She works for a company which makes medical equipment.", tokens: ["She works for a company", "making medical equipment."], ans: "She works for a company,making medical equipment." },
    { type: 6, raw1: "The road which connects the two towns is narrow.", tokens: ["The road", "connecting the two towns", "is narrow."], ans: "The road,connecting the two towns,is narrow." },
    { type: 6, raw1: "Anyone who breaks the rules will be punished.", tokens: ["Anyone", "breaking the rules", "will be punished."], ans: "Anyone,breaking the rules,will be punished." },
    { type: 6, raw1: "The guard who stands at the gate checks IDs.", tokens: ["The guard", "standing at the gate", "checks IDs."], ans: "The guard,standing at the gate,checks IDs." },
    { type: 6, raw1: "The boy who is standing by the door is my brother.", tokens: ["The boy", "standing by the door", "is my brother."], ans: "The boy,standing by the door,is my brother." },
    { type: 6, raw1: "The girls who are sitting under the tree are laughing.", tokens: ["The girls", "sitting under the tree", "are laughing."], ans: "The girls,sitting under the tree,are laughing." },
    { type: 6, raw1: "Look at the dog which is barking at the mailman.", tokens: ["Look at the dog", "barking at the mailman."], ans: "Look at the dog,barking at the mailman." },
    { type: 6, raw1: "Do you know the gentleman who is wearing a black suit?", tokens: ["Do you know the gentleman", "wearing a black suit?"], ans: "Do you know the gentleman,wearing a black suit?" },
    { type: 6, raw1: "The woman who is sitting near the window looks lonely.", tokens: ["The woman", "sitting near the window", "looks lonely."], ans: "The woman,sitting near the window,looks lonely." },
    { type: 6, raw1: "The cake that was made by my sister tasted sweet.", tokens: ["The cake", "made by my sister", "tasted sweet."], ans: "The cake,made by my sister,tasted sweet." },
    { type: 6, raw1: "The report which was written by Tom contains mistakes.", tokens: ["The report", "written by Tom", "contains mistakes."], ans: "The report,written by Tom,contains mistakes." },
    { type: 6, raw1: "The jacket which is made of leather is in the closet.", tokens: ["The jacket", "made of leather", "is in the closet."], ans: "The jacket,made of leather,is in the closet." },
    { type: 6, raw1: "I know a girl who speaks four languages.", tokens: ["I know a girl", "speaking four languages."], ans: "I know a girl,speaking four languages." },
    { type: 6, raw1: "The man who lives next door is a famous chef.", tokens: ["The man", "leaving next door", "is a famous chef."], ans: "The man,leaving next door,is a famous chef." }
];
